<?php

namespace Tests\Feature\Api;

use App\Jobs\SendAdScriptToN8n;
use App\Models\AdScriptTask;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Queue;
use Tests\TestCase;

class AdScriptTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Test creating a new ad script task.
     */
    public function test_can_create_ad_script_task(): void
    {
        Queue::fake();

        $user = User::factory()->create();
        $response = $this->actingAs($user, 'sanctum')->postJson('/api/ad-scripts', [
            'reference_script' => 'This is a sample advertising script that needs to be improved.',
            'outcome_description' => 'Make it more engaging and target young adults aged 18-25.',
        ]);

        $response->assertStatus(201)
            ->assertJsonStructure([
                'data' => [
                    'id',
                    'reference_script',
                    'outcome_description',
                    'status',
                    'created_at',
                    'updated_at',
                ],
            ]);

        $this->assertDatabaseHas('ad_script_tasks', [
            'status' => 'pending',
        ]);

        Queue::assertPushed(SendAdScriptToN8n::class);
    }

    /**
     * Test validation when creating a task.
     */
    public function test_validation_on_create(): void
    {
        $user = User::factory()->create();
        $response = $this->actingAs($user, 'sanctum')->postJson('/api/ad-scripts', [
            'reference_script' => 'Short',
            'outcome_description' => '',
        ]);

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['reference_script', 'outcome_description']);
    }

    /**
     * Test updating task result from n8n callback.
     */
    public function test_can_update_task_result(): void
    {
        $task = AdScriptTask::factory()->create([
            'status' => 'pending',
        ]);

        $response = $this->postJson("/api/ad-scripts/{$task->id}/result", [
            'new_script' => 'This is the improved script generated by AI.',
            'analysis' => 'The script was improved by making it more engaging and targeting the specified audience.',
        ]);

        $response->assertStatus(200)
            ->assertJsonStructure([
                'message',
                'task' => [
                    'id',
                    'status',
                    'new_script',
                    'analysis',
                ],
            ])
            ->assertJson([
                'message' => 'Task result updated successfully',
                'task' => [
                    'id' => $task->id,
                    'status' => 'completed',
                ],
            ]);

        $this->assertDatabaseHas('ad_script_tasks', [
            'id' => $task->id,
            'status' => 'completed',
            'new_script' => 'This is the improved script generated by AI.',
        ]);
    }

    /**
     * Test validation when updating task result.
     */
    public function test_validation_on_update_result(): void
    {
        $task = AdScriptTask::factory()->create();

        $response = $this->postJson("/api/ad-scripts/{$task->id}/result", [
            'new_script' => '',
            'analysis' => '',
        ]);

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['new_script', 'analysis']);
    }

    /**
     * Test showing a specific task.
     */
    public function test_can_show_task(): void
    {
        $user = User::factory()->create();
        $task = AdScriptTask::factory()->completed()->create();

        $response = $this->actingAs($user, 'sanctum')->getJson("/api/ad-scripts/{$task->id}");

        $response->assertStatus(200)
            ->assertJsonStructure([
                'task' => [
                    'id',
                    'reference_script',
                    'outcome_description',
                    'new_script',
                    'analysis',
                    'status',
                    'created_at',
                    'updated_at',
                ],
            ]);
    }

    /**
     * Test listing all tasks.
     */
    public function test_can_list_tasks(): void
    {
        $user = User::factory()->create();
        AdScriptTask::factory()->count(5)->create();

        $response = $this->actingAs($user, 'sanctum')->getJson('/api/ad-scripts');

        $response->assertStatus(200)
            ->assertJsonStructure([
                'data' => [
                    '*' => [
                        'id',
                        'reference_script',
                        'outcome_description',
                        'status',
                    ],
                ],
                'links',
                'meta',
            ]);

        $this->assertCount(5, $response->json('data'));
    }

    /**
     * Test that non-existent task returns 404.
     */
    public function test_show_non_existent_task_returns_404(): void
    {
        $user = User::factory()->create();
        $response = $this->actingAs($user, 'sanctum')->getJson('/api/ad-scripts/99999');

        $response->assertStatus(404);
    }

    /**
     * Test filtering tasks by status.
     */
    public function test_can_filter_tasks_by_status(): void
    {
        $user = User::factory()->create();
        AdScriptTask::factory()->count(3)->completed()->create();
        AdScriptTask::factory()->count(2)->failed()->create();
        AdScriptTask::factory()->count(1)->create(['status' => 'pending']);

        $response = $this->actingAs($user, 'sanctum')->getJson('/api/ad-scripts?status=completed');

        $response->assertStatus(200);
        $this->assertCount(3, $response->json('data'));
        $response->assertJsonPath('data.0.status', 'completed');
    }

    /**
     * Test searching tasks.
     */
    public function test_can_search_tasks(): void
    {
        $user = User::factory()->create();
        AdScriptTask::factory()->create([
            'reference_script' => 'Marketing script for product launch',
            'outcome_description' => 'Make it more engaging',
        ]);

        AdScriptTask::factory()->create([
            'reference_script' => 'Sales script for B2B',
            'outcome_description' => 'Professional tone',
        ]);

        $response = $this->actingAs($user, 'sanctum')->getJson('/api/ad-scripts?search=Marketing');

        $response->assertStatus(200);
        $this->assertGreaterThanOrEqual(1, count($response->json('data')));
    }

    /**
     * Test pagination limits.
     */
    public function test_pagination_respects_max_limit(): void
    {
        $user = User::factory()->create();
        AdScriptTask::factory()->count(150)->create();

        $response = $this->actingAs($user, 'sanctum')->getJson('/api/ad-scripts?per_page=200');

        $response->assertStatus(200);
        $this->assertLessThanOrEqual(100, count($response->json('data')));
    }

    /**
     * Test that completed task cannot be updated again.
     */
    public function test_completed_task_cannot_be_updated_again(): void
    {
        $task = AdScriptTask::factory()->completed()->create();

        $response = $this->postJson("/api/ad-scripts/{$task->id}/result", [
            'new_script' => 'New script',
            'analysis' => 'New analysis',
        ]);

        $response->assertStatus(409);
    }

    /**
     * Test health check endpoint.
     */
    public function test_health_check_returns_statistics(): void
    {
        AdScriptTask::factory()->count(5)->create(['status' => 'pending']);
        AdScriptTask::factory()->count(3)->completed()->create();
        AdScriptTask::factory()->count(2)->failed()->create();

        $response = $this->getJson('/api/ad-scripts/health');

        $response->assertStatus(200)
            ->assertJsonStructure([
                'status',
                'database',
                'statistics' => [
                    'pending',
                    'completed',
                    'failed',
                    'total',
                ],
                'timestamp',
            ])
            ->assertJson([
                'status' => 'healthy',
                'statistics' => [
                    'pending' => 5,
                    'completed' => 3,
                    'failed' => 2,
                    'total' => 10,
                ],
            ]);
    }

    /**
     * Test API key validation on callback endpoint.
     */
    public function test_callback_requires_api_key(): void
    {
        config(['services.n8n.api_key' => 'test-api-key']);

        $task = AdScriptTask::factory()->create();

        $response = $this->postJson("/api/ad-scripts/{$task->id}/result", [
            'new_script' => 'Test script',
            'analysis' => 'Test analysis',
        ]);

        $response->assertStatus(401);
    }

    /**
     * Test callback with valid API key.
     */
    public function test_callback_with_valid_api_key(): void
    {
        config(['services.n8n.api_key' => 'test-api-key']);

        $task = AdScriptTask::factory()->create();

        $response = $this->withHeader('X-N8N-API-KEY', 'test-api-key')
            ->postJson("/api/ad-scripts/{$task->id}/result", [
                'new_script' => 'Test script',
                'analysis' => 'Test analysis',
            ]);

        $response->assertStatus(200);
    }
}
